
### ejemplo de configuración de APISIX para enrutar peticiones a httpbin.org

### upstream
curl "http://127.0.0.1:9180/apisix/admin/upstreams/1" \
-H "X-API-KEY: nEIJ33AI1szXO7MIzLGTjQ5CIa4ZlYp3" -X PUT -d '
{
  "type": "roundrobin",
  "nodes": {
    "httpbin.org:80": 1
  }
}'

### routes
curl "http://127.0.0.1:9180/apisix/admin/routes/1" \
-H "X-API-KEY: nEIJ33AI1szXO7MIzLGTjQ5CIa4ZlYp3" -X PUT -d '
{
  "methods": ["GET"],
  "host": "example.com",
  "uri": "/anything/*",
  "upstream_id": "1"
}'

### vinculo la route con el upstream
curl "http://127.0.0.1:9180/apisix/admin/routes/1" \
-H "X-API-KEY: nEIJ33AI1szXO7MIzLGTjQ5CIa4ZlYp3" -X PUT -d '
{
  "methods": ["GET"],
  "host": "example.com",
  "uri": "/anything/*",
  "upstream": {
    "type": "roundrobin",
    "nodes": {
      "httpbin.org:80": 1
    }
  }
}'
### prueba

curl -i -X GET "http://127.0.0.1/anything/get?foo1=bar1&foo2=bar2" -H "Host: owsei.ddns.net"


######  

### creacion de local con mi dominio

### upstream
curl "http://127.0.0.1:9180/apisix/admin/upstreams/2" \
-H "X-API-KEY: nEIJ33AI1szXO7MIzLGTjQ5CIa4ZlYp3" -X PUT -d '
{
  "type": "roundrobin",
  "nodes": {
    "fastapi:8000": 1
  }
}'

### routes
curl "http://127.0.0.1:9180/apisix/admin/routes/2" \
-H "X-API-KEY: nEIJ33AI1szXO7MIzLGTjQ5CIa4ZlYp3" -X PUT -d '
{
  "methods": ["GET"],
  "host": "owsei.ddns.net",
  "uri": "/api/*",
  "plugins": {
    "proxy-rewrite": {
      "regex_uri": ["^/api/(.*)", "/$1"]
    }
  },
  "upstream_id": "2"
}'

### vinculo la route con el upstream
curl "http://127.0.0.1:9180/apisix/admin/routes/2" \
-H "X-API-KEY: nEIJ33AI1szXO7MIzLGTjQ5CIa4ZlYp3" -X PUT -d '
{
  "methods": ["GET"],
  "host": "owsei.ddns.net",
  "uri": "/test/*",
  "upstream": {
    "type": "roundrobin",
    "nodes": {
      "httpbin.org:80": 1
    }
  }
}'

###
curl -X GET "http://127.0.0.1:9092/v1/healthcheck" \
    -H "X-API-KEY: nEIJ33AI1szXO7MIzLGTjQ5CIa4ZlYp3"


### prueba
curl -i -X GET "http://127.0.0.1/api/docs" -H "Host: owsei.ddns.net"


######  

curl -i -X GET "http://127.0.0.1/api/" -H "Host: owsei.ddns.net"


###
curl -i -X GET "http://127.0.0.1:9100/apisix/admin/stream_routes" \
-H "X-API-KEY: nEIJ33AI1szXO7MIzLGTjQ5CIa4ZlYp3"


####

curl -i http://localhost:89/