version: '3.8'

networks:
  fiware:
    driver: bridge

volumes:
    mongoDBOrionPersist: ~

services:
  orion:
    image: telefonicaiot/fiware-orion
    ports:
      - "1026:1026"
    depends_on:
      - mongo
    command: 
      -dbURI mongodb://mongo
    networks:
     - fiware

  mongo:
    image: mongo:4.2
    container_name: mongo
    ports:
      - "27017:27017"
    command: 
      --nojournal
      --bind_ip_all 
    volumes:
      - mongoDBOrionPersist:/data/db
    networks:
      - fiware

  iot-agent:
    image: fiware/iotagent-json
    hostname: iot-agent-json
    container_name: iot-agent-json
    depends_on:
        - mongo
        - orion
    expose:
        - "4041"
        - "7896"
    environment:
        - "IOTA_CB_HOST=orion"
        - "IOTA_CB_PORT=1026"
        - "IOTA_NORTH_PORT=4041"
        - "IOTA_DEFAULT_RESOURCE=/iot/json"
        - "IOTA_REGISTRY_TYPE=mongodb"
        - "IOTA_MONGO_HOST=mongo"
        - "IOTA_MONGO_PORT=27017"
        - "IOTA_MONGO_DB=iotagent-json"
        - "IOTA_HTTP_PORT=7896"
        - "IOTA_PROVIDER_URL=http://iot-agent:4041"
    ports:
      - "4041:4041"
      - "7896:7896" # Puerto de recepción de datos UL
    networks:
      - fiware

  iot-agent-ul:
      image: fiware/iotagent-ul
      hostname: iot-agent-ul
      container_name: fiware-iot-agent-ul
      depends_on:
          - mongo
          - orion
      expose:
          - "4061"
          - "7897"
      ports:
          - "4061:4061"
          - "7897:7897"
      environment:
          - "IOTA_CB_HOST=orion"
          - "IOTA_CB_PORT=1026"
          - "IOTA_NORTH_PORT=4061"
          - "IOTA_DEFAULT_RESOURCE=/iot/ul"
          - "IOTA_REGISTRY_TYPE=mongodb"
          - "IOTA_MONGO_HOST=mongo"
          - "IOTA_MONGO_PORT=27017"
          - "IOTA_MONGO_DB=iotagent-ul"
          - "IOTA_HTTP_PORT=7897"
          - "IOTA_PROVIDER_URL=http://iot-agent:4061"