services:
  orion:
    image: telefonicaiot/fiware-orion
    ports:
      - "1026:1026"
    depends_on:
      - mongo
    command: -dbURI mongodb://mongo

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    command: --nojournal
    volumes:
      - mongo-db:/data

  cygnus:
    image: fiware/cygnus-ngsi
    hostname: cygnus
    container_name: fiware-cygnus
    networks:
      - default
    depends_on:
      - postgres-db
    ports:
      - "5050:5050"
      - "5051:5051"
      - "5055:5055"
      - "5080:5080" 
    environment:
      - "CYGNUS_POSTGRESQL_HOST=postgres-db" # Hostname of the PostgreSQL server used to persist historical context data
      - "CYGNUS_POSTGRESQL_PORT=5432" # Port that the PostgreSQL server uses to listen to commands
      - "CYGNUS_POSTGRESQL_USER=postgres" # Username for the PostgreSQL database user
      - "CYGNUS_POSTGRESQL_PASS=password" # Password for the PostgreSQL database user
      - "CYGNUS_POSTGRESQL_ENABLE_CACHE=false" # Switch to enable caching within the PostgreSQL configuration
      - "CYGNUS_POSTGRESQL_SERVICE_PORT=5055" # The port the agent.conf is configured for
      - "CYGNUS_LOG_LEVEL=DEBUG" # The logging level for Cygnus
      - "CYGNUS_SERVICE_PORT=5055" # Notification Port that Cygnus listens to for Postgres subscriptions
      - "CYGNUS_API_PORT=5080" 
      - "CYGNUS_MONGO_HOSTS= mongodb://localhost:27017"
      - "CYGNUS_MONGO_DB= orion"
      - "CYGNUS_MONGO_SERVICE_PORT=5051"
      - CYGNUS_MYSQL_HOST=mysql
      - CYGNUS_MYSQL_PORT=3306
      - CYGNUS_MYSQL_USER=cygnus
      - CYGNUS_MYSQL_PASS=cygnus
      - CYGNUS_MYSQL_DB=orion


  postgres-db:
    image: postgres
    hostname: postgres-db
    container_name: db-postgres
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=orion"
    volumes:
      - postgres-db:/var/lib/postgresql/data

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orion
      MYSQL_USER: cygnus
      MYSQL_PASSWORD: cygnus
    ports:
      - "3306:3306"
    restart: always

  sth-comet:
    image: telefonicaiot/fiware-sth-comet
    links:
      - mongo
    ports:
      - "8666:8666"
    environment:
      - STH_HOST=0.0.0.0
      - DB_URI=localhost:27017
    

volumes:
  mongo-db: 
  postgres-db: 