version: "3.8"

services:

  mongo-db:
    image: mongo:4.4
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:var/lib/mongodata
    networks:
      - fiware-net

  orion:
    image: fiware/orion:latest
    container_name: orion
    restart: always
    depends_on:
      - mongo-db
    ports:
      - "1026:1026"
    command: -dbURI mongodb://mongo-db
    networks:
      - fiware-net

  sth-comet:
    image: fiware/sth-comet:latest
    container_name: sth-comet
    restart: always
    depends_on:
      - mongo-db
    ports:
      - "8666:8666"
    environment:
      - DB_PREFIX=sth_
      - DB_URI=mongo-db:27017
    command: npm start
    networks:
      - fiware-net

  cygnus:
    image: fiware/cygnus-ngsi:latest
    container_name: cygnus
    restart: always
    depends_on:
      - mongo-db
      - orion
    ports:
      - "5051:5051"
      - "5055:5055"
      - "5080:5080" 
    environment:
      - "CYGNUS_POSTGRESQL_HOST=postgres-db" # Hostname of the PostgreSQL server used to persist historical context data
      - "CYGNUS_POSTGRESQL_PORT=5432" # Port that the PostgreSQL server uses to listen to commands
      - "CYGNUS_POSTGRESQL_USER=postgres" # Username for the PostgreSQL database user
      - "CYGNUS_POSTGRESQL_PASS=password" # Password for the PostgreSQL database user
      - "CYGNUS_POSTGRESQL_ENABLE_CACHE=false" # Switch to enable caching within the PostgreSQL configuration
      - "CYGNUS_POSTGRESQL_SERVICE_PORT=5055" # The port the agent.conf is configured for
      
      - "CYGNUS_LOG_LEVEL=DEBUG" # The logging level for Cygnus
      - "CYGNUS_API_PORT=5080" 
      
      - "CYGNUS_MONGO_HOSTS= localhost:27017"
      - "CYGNUS_MONGO_DB= orion"
      - "CYGNUS_MONGO_SERVICE_PORT=5051"
      
      - CYGNUS_MYSQL_HOST=mysql
      - CYGNUS_MYSQL_PORT=3306
      - CYGNUS_MYSQL_USER=admin
      - CYGNUS_MYSQL_PASS=1111
      - CYGNUS_MYSQL_DB=orion
    networks:
      - fiware-net

volumes:
  mongodb_data:

networks:
  fiware-net:
    driver: bridge
