version: '3.8'

networks:
  fiware:
    driver: bridge
volumes:
    mongodb: mongoDBOrionPersist
services:
  orion:
    image: telefonicaiot/fiware-orion
    ports:
      - "1026:1026"
    depends_on:
      - mongo
    command: 
      -dbURI mongodb://mongo
    networks:
     - fiware

  mongo:
    image: mongo:4.2
    container_name: mongo
    ports:
      - "27017:27017"
    command: 
      --nojournal
      --bind_ip_all 
    volumes:
      - mongodb:/data/db
    networks:
      - fiware

  iot-agent:
    image: fiware/iotagent-json
    hostname: iot-agent
    container_name: iot-agent
    depends_on:
        - mongo
        - orion
    expose:
        - "4041"
        - "7896"
    environment:
        - "IOTA_CB_HOST=orion"
        - "IOTA_CB_PORT=1026"
        - "IOTA_NORTH_PORT=4041"
        - "IOTA_DEFAULT_RESOURCE=/iot/json"
        - "IOTA_REGISTRY_TYPE=mongodb"
        - "IOTA_MONGO_HOST=mongo"
        - "IOTA_MONGO_PORT=27017"
        - "IOTA_MONGO_DB=iotagent-json"
        - "IOTA_HTTP_PORT=7896"
        - "IOTA_PROVIDER_URL=http://iot-agent:4041"
    ports:
      - "4041:4041"
      - "7896:7896" # Puerto de recepción de datos UL
    networks:
      - fiware

  # iot-agent-ul:
  #   image: fiware/iotagent-ul
  #   hostname: iot-agent-ul
  #   depends_on:
  #     - mongo
  #     - orion
  #   environment:
  #     - IOTA_LOG_LEVEL=DEBUG
  #     - IOTA_HTTP_PORT=4041
  #     - IOTA_DEFAULT_RESOURCE=/iot/ul
  #     - IOTA_REGISTRY_TYPE=mongodb
  #     - IOTA_MONGO_HOST=mongo
  #     - IOTA_MONGO_PORT=27017
  #     - IOTA_MONGO_DB=iotagentul
  #     - IOTA_NORTH_PORT=4041
  #     - IOTA_CB_HOST=orion
  #     - IOTA_CB_PORT=1026
  #     - IOTA_PROVIDER_URL=http://iot-agent-ul:4041
  #     - IOTA_AUTOCAST=true
  #     - IOTA_FALLBACK_TENANT=openiot
  #     - IOTA_MQTT_HOST=iot-agent-ul
  #     - IOTA_MQTT_PORT=1883
  #     - IOTA_MQTT_USERNAME=
  #     - IOTA_MQTT_PASSWORD=
  #     - IOTA_MQTT_KEEPALIVE=60
  #   ports:
  #     - "4041:4041"
  #     - "7896:7896" # Puerto de recepción de datos UL
  #     - "1883:1883" # MQTT (opcional, si se usa)
  #   networks:
  #     - fiware