services:
  nifi:
    image: apache/nifi
    container_name: nifi
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_WEB_HTTP_HOST= localhost
    volumes:
      - ./data/:/data
      - ./driver:/driver
      - ./content_repository:/opt/nifi/nifi-current/content_repository
      - ./database_repository:/opt/nifi/nifi-current/database_repository
      - ./extensions:/opt/nifi/nifi-current/extensions
      - ./flowfile_repopsitory:/opt/nifi/nifi-current/flowfile_respository
      - ./provenance_repository:/opt/nifi/nifi-current/provenance_repository
  
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: value
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/popstgres
    
    
    # docker run --name nifi -p 8443:8443 -d apache/nifi:latest


# Generated Username [4417ac98-1e06-42d3-960e-186276f5999e]
# Generated Password [amsEwBW64Ds2+WfoGw4hTLxgIhmhEs+Z]