
@host=localhost:1026

#********************* VERSIONES *****************************
#ORION VERSION
###
GET http://localhost:1026/version
###
GET http://localhost:1026/v2/types/
###
GET http://localhost:1026/v2/entities?id=*
###
###SUBSCRIPCIONES EN ORION DE CYGNUS
###
GET http://localhost:1026/v2/subscriptions/ HTTP/1.1

###
#VERSION IOT AGENT 
curl -X GET "http://localhost:4041/iot/about"
###

#VERSION IOT AGENT UL
curl -X GET "http://localhost:4061/iot/about"
###
#CYGNUS VERSION
GET http://localhost:5080/v1/version
###

###NIFI https
# curl -X GET 'https://localhost:9090/nifi-api/system-diagnostics'
curl -X GET https://localhost:8443/nifi-api/system-diagnostics
####

#********************* ORION *****************************
#ORION VERSION
GET http://localhost:1026/version
###
#ENTIDADES DADAS DE ALTA EN ORION
 ###
curl -X GET "http://localhost:1026/v2/entities/?options=keyValues" 
  -H 'fiware-service: pamplona' 
  -H 'fiware-servicepath:/urbanmovility ' 
###

curl -X GET "http://localhost:1026/v2/entities"

###
#AÑADIR ENTIDADES
curl -X POST 'http://localhost:1026/v2/entities/' 
-H 'Content-Type: application/json'
-d '{
        "id":"Room1",
        "type":"Room",
        "temperature":{
            "type":"Number",
            "value":25
        }
    }'
###

curl -X POST 'http://localhost:1026/v2/entities/' 
-H 'Content-Type: application/json' 
-d '{
        "id":"Room2",
        "type":"Room",
        "temperature":{
            "type":"Number",
            "value":23
        }
    }'
###

###BUSCAR ENTIDADES POR ID 
http://localhost:1026/v2/entities/41?options=keyValues

###
http://localhost:1026/v2/entities/Room2?options=keyValues
###

###************************************************************************
###***********************************************************************
###                          IoT Agent
###************************************************************************
###***********************************************************************

###SABER SI EL SERVICIO ESTA FUNCIONANDO
curl -X GET 'http://localhost:4041/iot/about'
###

###*************************************************************************

###CONFIGURAR DISPOSITIVOS JSON EN ORION IOTs
curl -X POST "http://localhost:4041/iot/services" \
  -H "Content-Type: application/json" \
  -H "fiware-service: pamplona" \
  -H "fiware-servicepath: /urbanmobility" \
  -d '{
    "services": [{
      "apikey": "123456789abcd",
      "cbroker": "http://orion:1026",
      "entity_type": "vehicle",
      "resource": "/iot/json"
    }]
  }'

###

curl -X POST "http://localhost:4041/iot/services" \
  -H "Content-Type: application/json" \
  -H "fiware-service: pamplona" \
  -H "fiware-servicepath: /urbanmobility" \
  -d '{
    "services": [{
      "apikey": "123456789abcd2",
      "cbroker": "http://orion:1026",
      "entity_type": "gtfsshape",
      "resource": "/iot/json"
    }]
  }'

### saber grupos de dispositivos registrados

curl -X GET 'http://localhost:4041/iot/services' \
  -H 'Fiware-Service: pamplona' \
  -H 'Fiware-ServicePath: /urbanmovility'


###**********************************************************************
###REGISTRAR DISPOSITIVOS JSON EN ORION
curl -X POST "http://localhost:4041/iot/devices" \
  -H "Content-Type: application/json" \
  -H "fiware-service: pamplona" \
  -H "fiware-servicepath: /urbanmovility" \
  -d '{
    "devices": [
      {
        "device_id": "Device002",
        "entity_name": "Vehicle",
        "entity_type": "Vehicle",
        "attributes": [
          { "object_id": "vehicleid", "name": "vehicleid", "type": "Number" },
          { "object_id": "h", "name": "humidity", "type": "text" }
        ],
        "static_attributes": [
          { "name": "location", "type": "geo:json", "value": "42.818372,-1.644066" }
        ],
        "protocol": "IoT-JSON",
        "apikey": "iot-json-key"
      }
    ]
  }'
###

###RECIBIR MEDIDAS
curl -iX POST 'http://localhost:7896/iot/json?k=jmyry5y4xzo34az90w71byics&i=Device001' \
  -H 'Content-Type: application/json' \
  -d '{"t":23,"h":55}'

###
curl -iX POST \
  'http://localhost:7896/iot/json?k=iot-json-key&i=roomparking001' \
  -H "Fiware-Service: pamplona" \
  -H "Fiware-ServicePath: /parking"
  -H 'Content-Type: application/json' \
  -d '{"t":25.5,"h":55}'
###

curl -X GET "http://localhost:1026/v2/entities" \
  -H "Fiware-Service: pamplona" \
  -H "Fiware-ServicePath: /urbanmovility"
###


###
###******************* CYGNUS******************************

###CYGNUS VERSION
http://localhost:5080/v1/version
####

http://pro-core-smc-cygnus:5080/v1/version

###
###SUBSCRIPCIONES EN ORION DE CYGNUS
curl -X GET http://localhost:1026/v2/subscriptions/ \
  -H "Fiware-Service: pamplona" \
###  -H "Fiware-ServicePath: /urbanmobility"\
###
curl -X GET http://localhost:1026/v2/subscriptions/ \
  -H "Fiware-Service: pamplona" \


###SUBCRIPCION PARA POSTGRES

curl -X POST 'http://localhost:1026/v2/subscriptions'\
  -H 'Content-Type: application/json' \
  -H "Fiware-Service: pamplona" \
  -H "Fiware-ServicePath: /urbanmobility"\
    -d '{
    "description": "Notify Cygnus of changes in IoT Agent",
    "subject": {
        "entities": [
          {
              "id": ".*"
          }
        ]
    },
    "notification": {
        "http": {
          "url": "http://cygnus:5055/notify"
        }
    },
    "throttling": 0,
    "covering":false
    }'
###
curl -X POST 'http://localhost:1026/v2/subscriptions'\
  -H 'Content-Type: application/json' \
  -H "Fiware-Service: pamplona" \
  -H "Fiware-ServicePath: /urbanmobility"\
    -d '{
    "description": "Notify Cygnus of changes in IoT Agent",
    "subject": {
        "entities": [
          {
              "id": ".*"
          }
        ]
    },
    "notification": {
        "httpCustom": {
          "url": "http://cygnus:5055",
          "headers": {
            "fiware-servicepath": "/urbanmobility"
          }
        },
        "attrs": [
          "TimeInstant",
          "vehicleid",
          "license_plate",
          "location",
          "timedata",
          "current_stop_sequence",
          "stop_id",
          "route_id",
          "trip_id",
          "direction_id",
          "occupancy_percentage"
        ]
    },
    "throttling": 0,
    "covering":false
    }'





###

###SUBCRIPCION PARA POSTGRES
### BUENA
curl -X POST 'http://localhost:1026/v2/subscriptions'\
  -H 'Content-Type: application/json' \
  -H "Fiware-Service: pamplona" \
  -H "Fiware-ServicePath: /urbanmobility"\
    -d '{
    "description": "Notify cygnus of changes in IoT Agent Timescale2",
    "subject": {
        "entities": [
        {
            "idPattern": ".*"
        }
      ]
    },
    "notification": {
        "http": {
        "url": "http://cygnus:5055/notify"
        }
    },
    "throttling": 0,
    "covering":false
    }'

###SUBCRIPCION PARA POSTGRES

curl -X POST 'http://localhost:1026/v2/subscriptions'\
  -H 'Content-Type: application/json' \
  -H "Fiware-Service: pamplona" \
  -H "Fiware-ServicePath: /urbanmobility"\
    -d '{
    "description": "Notify Cygnus of changes in IoT Agent",
    "subject": {
        "entities": [
          {
            "idPattern": ".*",
            "type": "vehicle"
          }
        ],
        "condition": {
        "attrs": [
          "TimeInstant"
        ],
        "notifyOnMetadataChange": true
      }
    },
    "notification": {
      "onlyChangedAttrs": false,
      "attrsFormat": "normalized",
        "http": {
          "url": "http://localhost:5055/notify"
        },
        "attrs": [
          "TimeInstant",
          "vehicleid",
          "license_plate",
          "location",
          "timedata",
          "current_stop_sequence",
          "stop_id",
          "route_id",
          "trip_id",
          "direction_id",
          "occupancy_percentage"
        ]
    },
    "throttling": 0,
    "covering":false
    }'
###

curl -iX POST \
  'http://localhost:1026/v2/subscriptions' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: pamplona' \
  -H 'fiware-servicepath: /urbanmobility' \
  -d '{
  "description": "Notify Draco 5060 of all context changes",
  "subject": {
    "entities": [
      {
        "idPattern": ".*",
        "type": "gtfsshape"
      }
    ]
  },
  "notification": {
    "http": {
      "url": "http://cygnus:5055/notify"
    }
  },
  "throttling": 0
}'
###

curl -iX POST \
  'http://localhost:1026/v2/subscriptions' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: pamplona' \
  -H 'fiware-servicepath: /urbanmobility' \
  -d '{
  "description": "Notify nifi of all context changes",
  "subject": {
    "entities": [
      {
        "idPattern": ".*"
      }
    ]
  },
  "notification": {
    "http": {
      "url": "http://cygnus:5055/notify"
    }
  },
  "throttling": 0
}'
###

###**************************************************************************

curl -X GET 'http://localhost:1026/v2/subscriptions'\
  -H 'fiware-service: pamplona' \
  -H 'fiware-servicepath: /iots' \
###
curl -X GET 'http://localhost:1026/v2/subscriptions'\
  -H 'fiware-service: pamplona' \
  -H 'fiware-servicepath: /urbanmobility' \
###

curl -X GET "http://localhost:1026/v2/entities/"
###

curl -X GET 'http://localhost:4041/iot/about'
###

http://localhost:1026/v2/entities/raiz:Sensor001?options=keyValues
###
http://localhost:1026/v2/entities/?options=keyValues
###
###ACTUALIZAR DATOS ENTIDAD 
curl -iX POST 'http://localhost:1026/v2/entities/room001/attrs' \
  -H 'Content-Type: application/json' \
  -H "Fiware-Service: pamplona" \
  -H "Fiware-ServicePath: /iots"
    -d '
    {
        "temperature": {"value": 30}
    }'
###

curl -X PATCH 'http://localhost:1026/v2/entities/Room1/attrs' \
-H 'Content-Type: application/json' \
-d '{
  "temperature": {
    "value": 66
  }
}'
###

curl -X PATCH 'http://localhost:1026/v2/entities/Room2/attrs' \
-H 'Content-Type: application/json' \
-d '{
  "temperature": {
    "value": 44
  }
}'

###

###
GET http://localhost:1026/v2/subscriptions/ HTTP/1.1
fiware-service: pamplona
fiware-servicepath: /iots
###

###
curl -iX POST \
  'http://localhost:1026/v2/subscriptions' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: pamplonaul' \
  -H 'fiware-servicepath: /' \
  -d '{
  "description": "Notify nifi of all context changes",
  "subject": {
    "entities": [
      {
        "idPattern": ".*"
      }
    ]
  },
  "notification": {
    "http": {
      "url": "http://localhost:5055/notify"
    }
  },
  "throttling": 0
}'



###
POST http://localhost:5050/notify HTTP/1.1
Fiware-Service: pamplona
Fiware-ServicePath: /iots
Content-Type: application/json

{
  "data": {
    "id": "Room1",
    "type": "Room",
    "temperature": {
      "value": 30,
      "type": "Number"
    }
  },
  "dataFormat": "keyValues",
  "originatorId": "Room1",
  "subscriptionId": "5f4e2b0c-3a7d-4b8e-9c3d-6f8a2b0c3a7d"
}


###
./opt/nifi/nifi-current/drivers/postgresql-42.2.4.jar


###



curl -X GET "http://localhost:81"\ 
-d '{"mensaje":"Hola mundo"}'
  